baseURL = 'https://shippoiincho.github.io/'
theme = "ananke"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
sectionPagesMenu = 'main'
title = 'しっぽいいんちょの作業メモ'
[params]
mainSections = ['blogs','docs']