baseURL = 'https://shippoiincho.github.io/'
theme = "ananke"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
sectionPagesMenu = 'main'
title = 'しっぽいいんちょの作業メモ'
[params]
mainSections = ['posts']
[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80
